# Common ROM version
ROM_VERSION_STABLE = 0
ROM_VERSION_BETA = 0
ROM_VERSION_ALPHA = 2

#Common build.prop overrides
PRODUCT_BUILD_PROP_OVERRIDES += BUILD_ID=IML74K BUILD_DISPLAY_ID=IML74K

BUILD_VERSION = $(ROM_VERSION_STABLE).$(ROM_VERSION_BETA).$(ROM_VERSION_ALPHA)

PRODUCT_PROPERTY_OVERRIDES += \
    ro.build.romversion=Crossbones-$(PRODUCT_DEVICE)-$(BUILD_VERSION)
